lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
collections:
  posts:
    output: true
show_drafts: null
limit_posts: 0
future: false
unpublished: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme 